"""
This type stub file was generated by pyright.
"""

"""
Copyright (C) 2012-2017, Leif Theden <leif.theden@gmail.com>

This file is part of pytmx.

pytmx is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

pytmx is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with pytmx.  If not, see <http://www.gnu.org/licenses/>.
"""
logger = ...
__all__ = ["load_pysdl2", "pysdl2_image_loader"]
flag_names = ...
def pysdl2_image_loader(renderer, filename, colorkey, **kwargs) -> Callable[..., tuple[Any, Any, Any | Literal[4, 0]] | tuple[Any, None, Literal[0]]]:
    ...

def load_pysdl2(renderer, filename, *args, **kwargs) -> TiledMap:
    ...

