"""
This type stub file was generated by pyright.
"""

import dataclasses
import pytmx
from typing import Tuple
from pygame.rect import Rect
from pygame._sdl2 import Renderer, Texture

"""
Copyright (C) 2012-2022, Leif Theden <leif.theden@gmail.com>

This file is part of pytmx.

pytmx is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

pytmx is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with pytmx.  If not, see <http://www.gnu.org/licenses/>.
"""
logger = ...
@dataclasses.dataclass(order=True)
class PygameSDL2Tile:
    texture: Texture
    srcrect: Rect
    size: Tuple[int, int]
    angle: float = ...
    center: None = ...
    flipx: bool = ...
    flipy: bool = ...


def handle_flags(flags: pytmx.TileFlags) -> tuple[Literal[270], Literal[False], Literal[False]] | tuple[Literal[90], Literal[False], Literal[False]] | tuple[float, Any, Any]:
    """
    Return angle and flip values for the SDL2 renderer

    """
    ...

def pygame_sd2_image_loader(renderer: Renderer, filename: str, colorkey, **kwargs) -> Callable[..., PygameSDL2Tile]:
    """
    pytmx image loader for pygame

    """
    ...

def load_pygame_sdl2(renderer: Renderer, filename: str, *args, **kwargs) -> TiledMap:
    """
    Load a TMX file, images, and return a TiledMap class

    """
    ...

